// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: visycvulzpfotsgkifdj

class SupabaseConfig {
  static const String supabaseUrl = 'https://visycvulzpfotsgkifdj.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpc3ljdnVsenBmb3RzZ2tpZmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3Mzc5NjEsImV4cCI6MjA3OTMxMzk2MX0.VQ2yGAxcXCk93k0SpbSHG3aciHR4GRXWtC5HTQqRvdg';
}
